;----------------------------------------------
;  Srexhsp.dll  header   (Ver2.5) By Sakura
;----------------------------------------------
	#uselib "Srexhsp.dll"

	#func active         active     2
	#func actwin         actwin     3
	#func btnable        btnable    2
	#func btngo          btngo      2
	#func btnout         btnout     2
	#func btntext        btntext    6
	#func captmode       captmode   2
	#func chengecur      chengecur  6
	#func childwin       childwin   2
	#func chkkigo        chkkigo    7
	#func clippos        clippos    0
	#func clipsize       clipsize   3
	#func coloful        coloful    2
	#func comaddstr      comaddstr  6
	#func combmake       combmake   2
	#func comcount       comcount   0
	#func comdelstr      comdelstr  0
	#func comexadd       comexadd   7
	#func comexmake      comexmake  2
	#func comfndstr      comfndstr  7
	#func comgetidx      comgetidx  3
	#func comgetstr      comgetstr  3
	#func cplrun         cplrun     0
	#func delfolder      delfolder  6
	#func deskcapt       deskcapt   2
	#func destroy        destroy    $100
	#func dosexec        dosexec    4
	#func doskeysnd      doskeysnd  0
	#func dragmode       dragmode   2
	#func drawcur        drawcur    6
	#func drawfsbox      drawfsbox  2
	#func dspcopy        dspcopy    0
	#func dspicon        dspicon    6
	#func dtpmake        dtpmake    2
	#func dtpset         dtpset     $13
	#func exabout        exabout    5
	#func exapend        exapend    $101
	#func excinfo        excinfo    3
	#func exdate         exdate     0
	#func exhinfo        exhinfo    2
	#func exlsbox        exlsbox    2
	#func exmove         exmove     2
	#func exmsbox        exmsbox    2
	#func exobjsel       exobjsel   2
	#func exojsize       exojsize   2
	#func exscset        exscset    2
	#func extask         extask     0
	#func exwinfo        exwinfo    3
	#func fdformat       fdformat   2
	#func fileicon       fileicon   6
	#func fontdlg        fontdlg    2
	#func fontinfo       fontinfo   $13
	#func formcl         formcl     2
	#func formdrag       formdrag   3
	#func formunaj       formunaj   2
	#func formx          formx      2
	#func fprodlg        fprodlg    6
	#func gdbox          gdbox      2
	#func getbmsize      getbmsize  7
	#func getchr         getchr     1
	#func getclip        getclip    2
	#func getcpu         getcpu     3
	#func getdvtype      getdvtype  $13
	#func getexname      getexname  7
	#func getfreesp      getfreesp  3
	#func getfsctl       getfsctl   $13
	#func gethwnd        gethwnd    $13
	#func geticon        geticon    7
	#func getlong        getlong    7
	#func getndrive      getndrive  7
	#func getplatos      getplatos  3
	#func getproces      getproces  3
	#func getrsrc        getrsrc    3
	#func getshort       getshort   7
	#func getsysdir      getsysdir  3
	#func getsysfol      getsysfol  3
	#func getsysres      getsysres  3
	#func gettbcmd       gettbcmd   2
	#func gettmpdir      gettmpdir  3
	#func getwinmem      getwinmem  3
	#func gfbox          gfbox      2
	#func gfcircle       gfcircle   2
	#func gfinit         gfinit     3
	#func gfline         gfline     2
	#func gfpaint        gfpaint    2
	#func gfrndbox       gfrndbox   2
	#func gverinfo       gverinfo   $16
	#func helpset        helpset    1
	#func helpword       helpword   6
	#func icondlg        icondlg    6
	#func icondraw       icondraw   2
	#func imgadd         imgadd     2
	#func imgclr         imgclr     0
	#func imgdraw        imgdraw    2
	#func imgicon        imgicon    0
	#func imgmake        imgmake    2
	#func imgobj         imgobj     2
	#func imgrgn         imgrgn     2
	#func imgrgn2        imgrgn2    2
	#func inpswd         inpswd     2
	#func ipaddctl       ipaddctl   2
	#func ipclradd       ipclradd   0
	#func ipgetadd       ipgetadd   $10
	#func ipiniset       ipiniset   3
	#func julius         julius     0
	#func kevent         kevent     0
	#func keystat        keystat    0
	#func keytgl         keytgl     0
	#func lsvcladd       lsvcladd   7
	#func lsvcldel       lsvcldel   0
	#func lsvcount       lsvcount   3
	#func lsvexset       lsvexset   0
	#func lsvfound       lsvfound   3
	#func lsvimadd       lsvimadd   7
	#func lsvimdel       lsvimdel   0
	#func lsvimget       lsvimget   3
	#func lsvimsel       lsvimsel   0
	#func lsvmake        lsvmake    2
	#func lsvsubadd      lsvsubadd  4
	#func makefile       makefile   6
	#func mcalcol        mcalcol    2
	#func mcalmake       mcalmake   2
	#func mcalset        mcalset    3
	#func menuadd        menuadd    6
	#func menubmp        menubmp    6
	#func menuchk        menuchk    0
	#func menudel        menudel    $100
	#func menudsp        menudsp    2
	#func menuimg        menuimg    6
	#func menuopt        menuopt    0
	#func menupop        menupop    3
	#func menusel        menusel    0
	#func menuset        menuset    2
	#func mevent         mevent     0
	#func mlsaddstr      mlsaddstr  6
	#func mlsallclr      mlsallclr  0
	#func mlsdelstr      mlsdelstr  6
	#func mlsgetcnt      mlsgetcnt  0
	#func mlsgetidx      mlsgetidx  3
	#func mlsgetstr      mlsgetstr  3
	#func mlsinsstr      mlsinsstr  6
	#func mlsselall      mlsselall  0
	#func mlstmake       mlstmake   2
	#func msgetpos       msgetpos   3
	#func mspos          mspos      2
	#func netdlg         netdlg     2
	#func netoff         netoff     0
	#func neton          neton      4
	#func objcolor       objcolor   2
	#func objcur         objcur     6
	#func objtipcol      objtipcol  2
	#func objtipfon      objtipfon  2
	#func objtips        objtips    6
	#func opndlg         opndlg     $16
	#func panelwnd       panelwnd   2
	#func popsmenu       popsmenu   3
	#func prnabort       prnabort   0
	#func prnbegin       prnbegin   6
	#func prncomdlg      prncomdlg  2
	#func prnend         prnend     $100
	#func prngeth        prngeth    3
	#func prninfo        prninfo    3
	#func prnpgdlg       prnpgdlg   2
	#func prnpgend       prnpgend   0
	#func prnpgset       prnpgset   0
	#func prntxtout      prntxtout  4
	#func progbar        progbar    2
	#func progcol        progcol    2
	#func progst         progst     2
	#func psdate         psdate     0
	#func pstime         pstime     0
	#func putclip        putclip    2
	#func resicon        resicon    2
	#func restdlg        restdlg    2
	#func scanrun        scanrun    0
	#func scrmode        scrmode    2
	#func selfoldlg      selfoldlg  $16
	#func skelton        skelton    2
	#func spinctl        spinctl    2
	#func spinrng        spinrng    0
	#func srexver        srexver    0
	#func strcase        strcase    3
	#func strcount       strcount   7
	#func strrevers      strrevers  7
	#func strstring      strstring  3
	#func strtoken       strtoken   7
	#func stsbar         stsbar     2
	#func stscell        stscell    3
	#func stsclr         stsclr     $100
	#func stscolor       stscolor   0
	#func stsicon        stsicon    2
	#func stsinf         stsinf     4
	#func tabadd         tabadd     6
	#func tabchild       tabchild   2
	#func tabmake        tabmake    2
	#func tabselget      tabselget  2
	#func taskclr        taskclr    0
	#func taskcmd        taskcmd    0
	#func taskopt        taskopt    0
	#func tasktry        tasktry    6
	#func tipcol         tipcol     2
	#func tipfont        tipfont    2
	#func tooladd        tooladd    2
	#func toolclr        toolclr    $100
	#func toolcmd        toolcmd    0
	#func tooldel        tooldel    2
	#func toolimg        toolimg    2
	#func toolopt        toolopt    2
	#func toolset        toolset    2
	#func toolstr        toolstr    6
	#func toolsys        toolsys    2
	#func tooltip        tooltip    6
	#func trackbar       trackbar   2
	#func trackget       trackget   0
	#func trackopt       trackopt   0
	#func trackpos       trackpos   0
	#func trackrng       trackrng   0
	#func treemake       treemake   2
	#func trvadd         trvadd     7
	#func trvcount       trvcount   3
	#func trvgetstr      trvgetstr  3
	#func trvimdel       trvimdel   0
	#func trvsort        trvsort    0
	#func wallset        wallset    4
	#func winshut        winshut    0
	#func wscenter       wscenter   2
	#func wsexec         wsexec     5
	#func wsexwin        wsexwin    2
	#func wsflash        wsflash    2
	#func wsicinf        wsicinf    2
	#func wsicon         wsicon     2
	#func wsmove         wsmove     2
	#func wsopicon       wsopicon   2
	#func wsrgn          wsrgn      2
	#func wszoom         wszoom     2
	#func xgrfcol        xgrfcol    2
	#func xgrfpos        xgrfpos    0
	#func xgrfset        xgrfset    2
	#func youbi          youbi      0


	#define TCN_SELCHANGE $1299



;------------------------------//EOF ------